### ISSUE TITLE
Not working as $routeMiddleware, only as global $middleware (Laravel 5.2)

### ISSUE THREAD

**Issue by pavoltanuska** [neomerx/cors-illuminate#12]
This is also written in the installation steps

> The middleware should be added to $middleware list which is executed for all routes

I'm just interested if this is by design and if so, then "why?".

Why should it be enabled globaly and not only for some routes (that I want provide CORS access to/from)?

Right now I'm treating the whole CORS as a black box, so maybe I'm asking wrong question :) Feel free to just point me in the right direction (docs or something) if you don't have time for explanations.

Thanks!

**Comment by neomerx** [comment]
Yes, you do :smile: 

Short answer: because of pre-flight requests. Browsers send requests to endpoints other than you've declared in your routes file. And app must correctly answer. So it is very reasonable to have middleware for all requests. Don't worry it's designed (by spec creators not me) to work with ordinary requests and it's implemented to be fast.
